# default rules
homepage:
    url: /
    param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
# default_index:
#   url:   /:module
#   param: { action: index }

# default:
#   url:   /:module/:action/*

# subirPadron:
#   url: /car/subirPadron/:autoId/:accion
#   param: {module:car,action:subirPadron}

# insurance_photos:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                InsurancePhotos
#     module:               insurancephotos
#     prefix_path:          /insurancephotos
#     column:               photo_id
#     with_wildcard_routes: true

# useradmin:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Useradmin
#     module:               useradmin
#     prefix_path:          /useradmin
#     column:               id
#     with_wildcard_routes: true

# transactiontype:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Transactiontype
#     module:               transactiontype
#     prefix_path:          /transactiontype
#     column:               id
#     with_wildcard_routes: true

# transaction:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Transaction
#     module:               transaction
#     prefix_path:          /transaction
#     column:               id
#     with_wildcard_routes: true

# state:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                State
#     module:               state
#     prefix_path:          /state
#     column:               id
#     with_wildcard_routes: true

# reporttype:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Reporttype
#     module:               reporttype
#     prefix_path:          /reporttype
#     column:               id
#     with_wildcard_routes: true

# report:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Report
#     module:               report
#     prefix_path:          /report
#     column:               id
#     with_wildcard_routes: true

# regiones:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Regiones
#     module:               regiones
#     prefix_path:          /regiones
#     column:               id
#     with_wildcard_routes: true

# rating:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Rating
#     module:               rating
#     prefix_path:          /rating
#     column:               id
#     with_wildcard_routes: true

# photos:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Photos
#     module:               photos
#     prefix_path:          /photos
#     column:               id
#     with_wildcard_routes: true

# model:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Model
#     module:               model
#     prefix_path:          /model
#     column:               id
#     with_wildcard_routes: true

# metodopago:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Metodopago
#     module:               metodopago
#     prefix_path:          /metodopago
#     column:               id
#     with_wildcard_routes: true

# message:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Message
#     module:               message
#     prefix_path:          /message
#     column:               id
#     with_wildcard_routes: true

# damages:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Damages
#     module:               damages
#     prefix_path:          /damages
#     column:               id
#     with_wildcard_routes: true

# country:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Country
#     module:               country
#     prefix_path:          /country
#     column:               id
#     with_wildcard_routes: true

# conversation:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Conversation
#     module:               conversation
#     prefix_path:          /conversation
#     column:               id
#     with_wildcard_routes: true

# comunas:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Comunas
#     module:               comunas
#     prefix_path:          /comunas
#     column:               codigointerno
#     with_wildcard_routes: true

# city:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                City
#     module:               city
#     prefix_path:          /city
#     column:               id
#     with_wildcard_routes: true

# brand:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Brand
#     module:               brand
#     prefix_path:          /brand
#     column:               id
#     with_wildcard_routes: true

# availability:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Availability
#     module:               availability
#     prefix_path:          /availability
#     column:               Array
#     with_wildcard_routes: true

# reserve:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Reserve
#     module:               reserve
#     prefix_path:          /reserve
#     column:               id
#     with_wildcard_routes: true

# car:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Car
#     module:               car
#     prefix_path:          /car
#     column:               id
#     with_wildcard_routes: true
    
# user:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                User
#     module:               user
#     prefix_path:          /user
#     column:               id
#     with_wildcard_routes: true

    
# users2Excel:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Users2Excel
#     module:               user2Excel
#     prefix_path:          /users2Excel
#     column:               id
#     with_wildcard_routes: true    

# dashboard:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                Dashboard
#     module:               dashboard
#     prefix_path:          /dashboard
#     column:               id
#     with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#sfGuardAuth
# sf_guard_signin:
#   url:   /ingresar
#   param: { module: sfGuardAuth, action: signin }

# sf_guard_signout:
#   url:   /salir
#   param: { module: sfGuardAuth, action: signout }

# sf_guard_password:
#   url:   /recuperar-password
#   param: { module: sfGuardAuth, action: password }
