# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: main, action: index }

car_is_active_car:
    url: /vehiculo/es-vehiculo-activo
    param: { module: car, action: isActiveCar }

car_get_actives_cars:
    url: /vehiculo/vehiculos-activos
    param: { module: car, action: getActivesCars }

comment:
    url: /comentario/:userId/:managementId
    param: { module: main, action: comment }

commentDo:
    url: /comentario/hacer
    param: { module: main, action: commentDo }

login:
    url: /login
    param: { module: main, action: login }

login_do:
    url: /login/do
    param: { module: main, action: loginDo }

logout:
    url: /logout
    param: { module: main, action: logout }

opportunity_create:
    url: /oportunidades/crear
    param: { module: opportunity, action: create }

opportunity_mailing:
    url: /oportunidades/mailing
    param: { module: opportunity, action: mailing }

opportunity_mailing_config_save:
    url: /oportunidades/mailing/guardar
    param: { module: opportunity, action: mailingConfigSave }

reserve_is_original_reserve:
    url: /reserva/es-reserva-original
    param: { module: reserve, action: isOriginalReserve }

user_without_car:
    url: /usuarios/sin-vehiculo/
    param: { module: user, action: whitoutCar }

user_without_car_get:
    url: /usuarios/sin-vehiculo/obtener
    param: { module: user, action: whitoutCarGet }

user_without_pay:
    url: /usuarios/sin-pago
    param: { module: user, action: whitoutPay }

user_without_pay_get:
    url: /usuarios/sin-pago/obtener
    param: { module: user, action: whitoutPayGet }






