# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: main, action: index }

car_control:
    url: /auto/control-auto
    param: { module: car, action: carControl}

car_delete_damage:
    url: /auto/eliminar-dano
    param: { module: car, action: deleteDamage }

car_find_all:
    url: /auto/buscar-todos
    param: { module: car, action: findAll }

car_find_car:
    url: /auto/buscar
    param: { module: car, action: findCar }

car_find_damage:
    url: /auto/buscar-dano
    param: { module: car, action: findDamage }

car_get_actives_cars:
    url: /auto/autos-activos
    param: { module: car, action: getActivesCars }

car_is_active_car:
    url: /auto/es-auto-activo
    param: { module: car, action: isActiveCar }

car_save_accessories:
    url: /auto/guardar-accesorios
    param: { module: car, action: saveAccessories }

car_save_audio_accessories:
    url: /auto/guardar-accesorios-audio
    param: { module: car, action: saveAudioAccessories }

car_save_damage:
    url: /auto/guardar-dano
    param: { module: car, action: saveDamage }

car_verify_car:
    url: /auto/verificar
    param: { module: car, action: verifyCar }

gps_control:
    url: /gps/control
    param: { module: gps, action: carsUploadWithoutGps }

gps_find_all:
    url: /gps/buscar-todos
    param: { module: gps, action: carFindAll }

gps_generate_pay:
    url: /gps/generar-pago
    param: { module: gps, action: generatePay }

comment:
    url: /comentario/:userId/:managementId
    param: { module: main, action: comment }

commentDelete:
    url: /comentario/eliminar
    param: { module: main, action: commentDelete }

commentDo:
    url: /comentario/hacer
    param: { module: main, action: commentDo }

login:
    url: /login
    param: { module: main, action: login }

login_do:
    url: /login/do
    param: { module: main, action: loginDo }

logout:
    url: /logout
    param: { module: main, action: logout }

notification:
    url: /administrador-notificaciones
    param: {module: notification, action: index }

notification_find_notification:
    url: /administrador-notificaciones/buscar-notificaciones
    param: {module: notification, action: findNotification }

notification_edit_notification:
    url: /administrador-notificaciones/editar-notificaciones
    param: {module: notification, action: editNotification }

notification_management_action:
    url: /administrador-acciones 
    param: {module: notification, action: managementAction }

notification_management_action_crud:
    url: /administrador-acciones/crud
    param: {module: notification, action: managementActionCrud }

notification_management_notification_type:
    url: /administrador-tipos-notificaciones 
    param: {module: notification, action: managementNotificationType}

notification_management_notification_type_crud:
    url: /administrador-tipos-notificaciones/crud
    param: {module: notification, action: managementNotificationTypeCrud}

opportunity_create:
    url: /oportunidades/crear
    param: { module: opportunity, action: create }

opportunity_dashboard:
    url: /oportunidades
    param: { module: opportunity, action: index }

opportunity_kpi_refresh:
    url: /oportunidades/kpi/refrescar
    param: { module: opportunity, action: kpiRefresh }

opportunity_mailing_config_save:
    url: /oportunidades/mailing/guardar
    param: { module: opportunity, action: mailingConfigSave }

reserve_edit:
    url: /reserva/editar-reserva
    param: { module: reserve, action: editReserve}

reserve_expired_reserves:
    url: /reserva/reserveas-vencidad
    param: { module: reserve, action: expiredReserves}

reserve_find_expired_reserves:
    url: /reserva/buscar-reserveas-vencidad
    param: { module: reserve, action: findExpiredReserves}

reserve_find_problematic_reserves:
    url: /reserva/buscar-reservas-problematicas 
    param: { module: reserve, action: findProblematicReserves}

reserve_fortnightly_Payments:
    url: /reserva/pagos-quincenales
    param: { module: reserve, action: fortnightlyPayments}

reserve_is_original_reserve:
    url: /reserva/es-reserva-original
    param: { module: reserve, action: isOriginalReserve }

reserve_problematic_reservations:
    url: /reserva/reservas-problematicas 
    param: { module: reserve, action: problematicReservations }

transaction_edit:
    url: /transaction/editar-transaccion
    param: { module: transaction, action: editTransaction }

user_change_call:
    url: /usuarios/cambiar-llamado
    param: { module: user, action: changeCall }

user_control:
    url: /usuarios/control-usuario
    param: { module: user, action: userControl }

user_edit:
    url: /usuarios/editar-usuario
    param: { module: user, action: editUser }

user_edit_account:
    url: /usuarios/editar-usuario-cuenta
    param: { module: user, action: editUserAccount }

user_find_all:
    url: /usuarios/buscar-todos
    param: { module: user, action: userFindAll }

user_upload_photo:
    url: /usuarios/subir-foto
    param: { module: user, action: uploadPhoto }

user_whitout_car:
    url: /usuarios/sin-auto
    param: { module: user, action: whitoutCar }

user_whitout_car_get:
    url: /usuarios/sin-auto/obtener
    param: { module: user, action: whitoutCarGet }

user_whitout_pay:
    url: /usuarios/sin-pago
    param: { module: user, action: whitoutPay }

user_whitout_pay_get:
    url: /usuarios/sin-pago/obtener
    param: { module: user, action: whitoutPayGet }

upload_photo:
    url: /subir-foto
    param: { module: car, action: uploadPhoto }






