# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  path_reserve_videos: reserve/videos
  path_reserve_images: reserve/images
  image_size_max: 100000
  image_size_min: 500
  video_size_max: 100000
  video_size_min: 1000
