# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

userLogin:
    url: /user/login
    param: { module: user, action: login }

userForgot:
    url: /user/forgot
    param: { module: user, action: forgot }

userCurrentReserve:
    url: /user/:user_id/reserve/current
    param: { module: user, action: currentReserve }

userCurrentReserveInitialized:
    url: /user/:user_id/reserve/current_initialized
    param: { module: user, action: currentReserveInitialized }

userOne:
    url: /user/:id
    param: { module: user, action: one }
    requirements:
        sf_method: [GET]    

reserveInitializePostVideo:
    url: /reserve/:reserve_id/initialize/video
    param: { module: reserve, action: initializePostVideo }
    requirements:
        sf_method: [POST]

reserveFinalizePostVideo:
    url: /reserve/:reserve_id/finalize/video
    param: { module: reserve, action: finalizePostVideo }
    requirements:
        sf_method: [POST]

reservePostLicenceImage:
    url: /reserve/:reserve_id/licence_image
    param: { module: reserve, action: postLicenceImage }
    requirements:
        sf_method: [POST]

reserveInitializePostCarPanelImage:
    url: /reserve/:reserve_id/initialize/car_panel_image
    param: { module: reserve, action: initializePostCarPanelImage }
    requirements:
        sf_method: [POST]

reserveFinalizePostCarPanelImage:
    url: /reserve/:reserve_id/finalize/car_panel_image
    param: { module: reserve, action: finalizePostCarPanelImage }
    requirements:
        sf_method: [POST]

reserveOwner:
    url: /reserve/:id/owner
    param: { module: reserve, action: owner }
    requirements:
        sf_method: [GET]

reserveOne:
    url: /reserve/:id
    param: { module: reserve, action: one }
    requirements:
        sf_method: [GET]

    

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
