# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions
      auto_start: false

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

#   mailer:
#     param:
#       delivery_strategy: none

# dev:
#   mailer:
#     param:
#       delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: spool
      spool_class:       Swift_FileSpool
      spool_arguments:   [ %SF_ROOT_DIR%/spool ]
      transport:
        class: Swift_SmtpTransport
        param:
          host:       email-smtp.us-east-1.amazonaws.com
          port:       25
          encryption: tls
          username:   AKIAJRRM5T4IKKLOSENA
          password:   Akg+kowIIe25c5kq2L/6zq+WD1+3TQEqw0mHoWGoTIa9

  storage:
    class: sfSessionStorage
    param:
      session_name: Arriendas
      session_cookie_domain: .arriendas.cl
