reserves:
    url: /reservas
    param: { module: profile, action: reserves }

reserve_change:
    url: /reserve/change
    param: { module: profile, action: reserveChange }

reserve_extend:
    url: /reserve/extend
    param: { module: profile, action: reserveExtend }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
user_register_complete:
    url: /registro/completar/
    param: { module: main, action: completeRegister }

user_register:
    url: /registro
    param: { module: main, action: register }

index_by_city:
  url:    /c/:c
  param:  { module: main, action: index }

perfil_auto:
    url:  /arriendo-de-autos/rent-a-car/*/:chile/:id
    param:  { module: auto, action: economico }

paypalReturn:
    url:  /paypal/processPayment
    param:  { module: paypal, action: processPayment }

paypalCancel:
    url:  /paypal/processPaymentCanceled
    param:  { module: paypal, action: processPaymentCanceled }

webpayReturn:
    url:  /webpay/processPayment
    param:  { module: webpay, action: processPayment }

webpayCancel:
    url:  /webpay/processPaymentCanceled
    param:  { module: webpay, action: processPaymentCanceled }

webpayFinal:
    url:  /webpay/processPaymentFinal
    param:  { module: webpay, action: processPaymentFinal }

khipuNotify:
    url:  /khipu/notifyPayment
    param:  { module: khipu, action: notifyPayment }
khipuReturn:
    url:  /khipu/paymentInformation
    param:  { module: khipu, action: paymentInformation }
khipuCancel:
    url:  /khipu/processPaymentCanceled
    param:  { module: khipu, action: processPaymentCanceled }

pedidos:
    url: /profile/pedidos
    param:  { module: profile, action: pedidos }

editReserve:
    url: /profile/editReserve
    param:  { module: profile, action: editReserve }

aprobarReserve:
    url:  /profile/aprobarReserve/:idReserve/:idUser
    param:  { module: profile, action: aprobarReserve }

aprobarOportunidad:
    url:  /profile/aprobarOportunidad/:idReserve/:idCar/:idUser
    param:  { module: profile, action: aprobarOportunidad }

checkOpenedEmail:
    url: /img
    param: { module: main, action: openOpportunityEmail }

opportunityAccept:
    url: /accept
    param: { module: profile, action: oportunidadAceptar }

availability:
    url: /availability
    param: { module: main, action: availability }

availabilityEmailOpen:
    url: /availability/open
    param: { module: main, action: availabilityOpen }

facebook_login:
    url: /main/loginFacebook 
    param:  { module: main, action: loginFacebook }

# URLs específicas para cada region-comuna
region-comuna:
    url: /arriendo-de-autos/:region/:comuna
    param: {module: main, action: index }
 
# default rules
homepage:
  url:   /
  param: { module: main, action: index }

fbShare:
  url:    /fb/:id/
  param:  { module: main, action: fbShare }
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*




