# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

test_khipu:
    url: /test/khipu
    param: { module: main, action: testKhipu }

about_company:
    url: /nosotros
    param: { module: main, action: compania }

car_price:
   url: /auto/precios
   param: { module: cars, action: price }

car_photo:
   url: /auto/foto
   param: { module: cars, action: photo }

car_create:
   url: /auto/crear
   param: { module: cars, action: create }

car_availability:
   url: /auto/disponibilidad
   param: { module: cars, action: availability }

cars:
    url: /mis-autos
    param: { module: profile, action: cars }
    #param: { module: cars, action: index }

forgot_password:
    url: /recuperar-contrasena
    param: { module: main, action: forgot }

homepage:
    url: /
    param: { module: main, action: index }

login:
    url: /login
    param: { module: main, action: login }

login_do:
    url: /login/do
    param: { module: main, action: loginDo }

logout:
    url: /logout
    param: { module: main, action: logout }

messages:
    url: /mensajes/:id
    param: { module: messages, action: conversation }

messages_inbox:
    url: /mis-mensajes
    param: { module: messages, action: inbox }

opportunities:
    url: /oportunidades
    param: { module: opportunities, action: index }

opportunities_approve:
    url: /oportunidades/aprobar
    param: { module: opportunities, action: approve }

opportunities_mailing_approve:
    url: /oportunidades/mailing/aprobar/:reserve_id/:car_id/:signature
    param: { module: opportunities, action: mailingApprove }

opportunities_mailing_open:
    url: /oportunidades/mailing/:id/:signature
    param: { module: main, action: mailingOpen }

questions:
    url: /preguntas-frecuentes
    param: { module: main , action: questions }

rent_a_car_region_commune:
    url: /arriendo-de-autos/:region/:commune
    param: {module: main, action: index }

reserve:
    url: /reserva/auto/:carId
    param: { module: main, action: reserve }

reserve_approve:
    url: /reserva/aprobar
    param: { module: reserves, action: approve }

reserve_change:
    url: /reserva/cambiar
    param: { module: reserves, action: change }

reserve_extend:
    url: /reserva/extender
    param: { module: reserves, action: extend }

reserve_extend_get_price:
    url: /reserva/extender/obtenerPrecio
    param: { module: reserves, action: getExtendPrice }

reserve_pay:
    url: /reserva/pagar
    param: { module: reserves, action: pay }

reserve_reject:
    url: /reserva/rechazar
    param: { module: reserves, action: reject }

reserves:
    url: /reservas
    param: { module: reserves, action: index }

return_form:
    url: /informe-de-devolucion/:tokenReserve
    param: { module: main, action: generarFormularioEntregaDevolucion }

terms_and_conditions:
    url: /terminos-y-condiciones
    param: { module: main, action: terminos }

transactions:
    url: /mis-transacciones
    param: { module: profile, action: transactions }

user_register:
    url: /registro
    param: { module: main, action: register }

user_register_complete:
    url: /registro/completar
    param: { module: main, action: completeRegister }

# old Design

index_by_city:
  url:    /c/:c
  param:  { module: main, action: index }

perfil_auto:
    url:  /arriendo-de-autos/rent-a-car/*/:chile/:id
    param:  { module: auto, action: economico }

paypalReturn:
    url:  /paypal/processPayment
    param:  { module: paypal, action: processPayment }

paypalCancel:
    url:  /paypal/processPaymentCanceled
    param:  { module: paypal, action: processPaymentCanceled }

webpayReturn:
    url:  /webpay/processPayment
    param:  { module: webpay, action: processPayment }

webpayCancel:
    url:  /webpay/processPaymentCanceled
    param:  { module: webpay, action: processPaymentCanceled }

webpayFinal:
    url:  /webpay/processPaymentFinal
    param:  { module: webpay, action: processPaymentFinal }

khipuNotify:
    url:  /khipu/notifyPayment
    param:  { module: khipu, action: notifyPayment }

khipuReturn:
    url:  /khipu/paymentInformation
    param:  { module: khipu, action: paymentInformation }

khipuCancel:
    url:  /khipu/processPaymentCanceled
    param:  { module: khipu, action: processPaymentCanceled }

pedidos:
    url: /profile/pedidos
    param:  { module: profile, action: pedidos }

editReserve:
    url: /profile/editReserve
    param:  { module: profile, action: editReserve }

aprobarReserve:
    url:  /profile/aprobarReserve/:idReserve/:idUser
    param:  { module: profile, action: aprobarReserve }

aprobarOportunidad:
    url:  /profile/aprobarOportunidad/:idReserve/:idCar/:idUser
    param:  { module: profile, action: aprobarOportunidad }

availability:
    url: /availability
    param: { module: main, action: availability }

availabilityEmailOpen:
    url: /availability/open
    param: { module: main, action: availabilityOpen }

facebook_login:
    url: /main/loginFacebook 
    param:  { module: main, action: loginFacebook }

fbShare:
  url:    /fb/:id/
  param:  { module: main, action: fbShare }

# generic rules
# please, remove them by adding more specific rules
# default_index:
#   url:   /:module
#   param: { action: index }

default:
  url:   /:module/:action/*
