generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Reporttype
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          reporttype
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Marcas de Autos
        max_per_page: 100
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
