generator:
  class: sfDoctrineGenerator
  param:
    model_class:           InsurancePhotos
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          insurance_photos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        title: Fotos Aseguradora
        fields:
          frontal_der:
            name: frontal_der
            help: Frontal Costado Derecho
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          frontal_izq:
            name: frontal_izq
            help: Frontal Costado Izquierdo
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          frontal_cen:
            name: frontal_cen
            help: Frontal Central
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          trasera_der:
            name: trasera_der
            help: Trasera Costado Derecho
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          trasera_izq:
            name: trasero_izq
            help: Trasera Costado Izquierdo
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          trasera_cen:
            name: trasera_cen
            help: Trasera Central
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          lateral_izq:
            name: lateral_izq
            help: Costado Izquierdo
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          lateral_der:
            name: lateral_der
            help: Costado Derecho
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          llanta_del_izq:
            name: llanta_del_izq
            help: Llanta Delantera Izquierdo
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          llanta_del_der:
            name: llanta_del_der
            help: Llanta Delentera Derecha
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          llanta_tra_izq:
            name: llanta_tra_izq
            help: Llanta Trasera Izquierda
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          llanta_tra_der:
            name: llanta_tra_der
            help: Llanta Trasera Derecha
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          equipo_audio:
            name: equipo_audio
            help: Equipo de Audio
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
          tablero:
            name: tablero
            help: Panel
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true  
          padron:
            name: padron
            help: foto del padron
            type: admin_input_file_tag
            upload_dir: pictures/insurance
            params: include_link=pictures/insurance include_remove=true
      new:     ~
