generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Car
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          car
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields:
      list:
        max_per_page: 1000
        title: Listado de Autos Registrados
        display: [User,patente,consultas,Ownername,Ownerlastname,Useremail,Userphone,address,City,Price_per_hour,Price_per_day,Model,Year,wid_padron,wid_frontal_izq,wid_frontal_cen,wid_frontal_der,wid_trasera_izq,wid_trasera_cen,wid_trasera_der,wid_lateral_der,wid_lateral_izq,wid_tablero,wid_equipo_audio,wid_llanta_del_izq,wid_llanta_del_der,wid_llanta_tra_izq,wid_llanta_tra_der,wid_dagnos]
        fields:
          User_Name: {label: Propietario}
          wid_padron: {label: Padron}
          wid_frontal_izq: {label: Frontal Izquierda}
          wid_frontal_cen: {label: Frontal Central}
          wid_frontal_der: {label: Frontal Derecha}
          wid_trasera_izq: {label: Trasera Izquierda}
          wid_trasera_cen: {label: Trasera Central}
          wid_trasera_der: {label: Trasera Derecha}
          wid_lateral_izq: {label: Lateral Izquierda}
          wid_lateral_der: {label: Lateral Derecha}
          wid_tablero: {label: Tablero}
          wid_equipo_audio: {label: Equipo Audio}
          wid_llanta_del_izq: {label: Llanta Delantera Der}
          wid_llanta_del_der: {label: Llanta Delantera Izq}
          wid_llanta_tra_izq: {label: Llanta Trasera Izq}
          wid_llanta_tra_der: {label: Llanta Trasera Der}
          wid_dagnos: {label: Da&ntilde;os} 
      filter:  ~
      form:    ~
      edit:
        title: Modificar Auto
      new:     ~
      show:    ~
