# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: main, action: index }

login:
    url: /login
    param: { module: main, action: login }

login_do:
    url: /login/do
    param: { module: main, action: loginDo }

logout:
    url: /logout
    param: { module: main, action: logout }

notification:
    url: /notificaciones
    param: {module: notification, action: index}

notification_create:
    url: /notificaciones/crear
    param: {module: notification, action: create}

notification_edit:
    url: /notificaciones/editar
    param: {module: notification, action: edit}    

notification_find:
    url: /notificaciones/buscar
    param: {module: notification, action: find}


