all:
    is_secure: false

login:
    is_secure: false

login_do:
    is_secure: false

logout:
    is_secure: false

opportunities_mailing_open:
    is_secure: false

reserve:
    is_secure: true
