agradecimientoSuccess:
    layout: simple
    
subirImagenS3Success:
    layout: basic

informeDaniosSuccess:
    layout: basic
    
reporteDaniosSuccess:
    layout: basic
    
reporteResumenSuccess:
    layout: basic
    
formularioEntregaSuccess:
    layout: basic
    
upload2S3Success:
    layout: basic

companiaSuccess:
    metas:
        description:  Creemos en el valor de compartir y en poder acceder a un auto sin la necesidad de comprarlo.