car_availability_remove:
    is_secure: true

car_availability_save:
    is_secure: true

car_set_active:
    is_secure: true

car_set_option:
    is_secure: true

car_set_disabled_until:
    is_secure: true

car_price:
    is_secure: true

car_photo:
    is_secure: true

car_edit:
    is_secure: true

car_create:
    is_secure: true

car_availability:
    is_secure: true

cars:
    is_secure: true