settings:
  dev:
   create-payment-url: https://khipu.com/api/1.2/createAuthenticatedPaymentURL
   notification-validation-url: https://khipu.com/api/1.2/verifyPaymentNotification
   payment-status-url: https://khipu.com/api/1.2/paymentStatus
   receiver_id: 8747
   secret: bdc660812414fdc5166b8cdbe603cddbee3ce5d4
   status_success: Success
   status_success_warning: SuccessWithWarning
   status_failure: Failure
   status_failure_warning: FailureWithWarning
  prod:
   create-payment-url: https://khipu.com/api/1.2/createAuthenticatedPaymentURL
   notification-validation-url: https://khipu.com/api/1.2/verifyPaymentNotification
   payment-status-url: https://khipu.com/api/1.2/paymentStatus
   receiver_id: 9139
   secret: 28f249db82f364a8f5c59b27558f07876ea4eec0
   status_success: Success
   status_success_warning: SuccessWithWarning
   status_failure: Failure
   status_failure_warning: FailureWithWarning