settings:
    dev:
        create-payment-url: https://khipu.com/api/1.3/createPaymentURL
        notification-validation-url: https://khipu.com/api/1.3/verifyPaymentNotification
        payment-status-url: https://khipu.com/api/1.3/paymentStatus
        receiver_id: 9139
        secret: 28f249db82f364a8f5c59b27558f07876ea4eec0
        status_success: Success
        status_success_warning: SuccessWithWarning
        status_failure: Failure
        status_failure_warning: FailureWithWarning
    prod:
        create-payment-url: https://khipu.com/api/1.3/createPaymentURL
        notification-validation-url: https://khipu.com/api/1.3/verifyPaymentNotification
        payment-status-url: https://khipu.com/api/1.3/paymentStatus
        receiver_id: 41063
        secret: 4cd49047ab0884679dd996f7080990319865d5c9
        status_success: Success
        status_success_warning: SuccessWithWarning
        status_failure: Failure
        status_failure_warning: FailureWithWarning