generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields: 
        lastname: { label: Apellidos } 
        firstname: { label: Nombres }
        email: { label: E-Mail }
        telephone: { label: Fono }
        facebook_id: { label: Usr Facebook }
        address: { label: Dirección }
        confirmed: { label: Confirmado }
        confirmed_fb: { label: FB Confirmado }
        propietario: { label: Propietario, is_real: true }
        picture_file: { label: Foto}
        driver_license_file: { label: F. Lic.}
        rut_file: { label: F. RUT}
      list:
        max_per_page: 1000
        title: Listado de Usuarios
        display: [=Id,lastname,firstname,email,telephone,facebook_id,address,confirmed,propietario,messages,recommender,picture_file,driver_license_file,rut_file]
        table_method: getUsuariosAutos
      filter:
        display: [lastname,firstname,email,confirmed,propietario]
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
