index:
    is_secure: true

opportunities_approve:
    is_secure: true

opportunities_mailing_approve:
    is_secure: false

opportunities_mailing_open:
    is_secure: false

opportunities_approve:
    is_secure: true