settings:
  dev:
   url: http://201.238.207.131:7003/WSWebpayTransaction/cxf/WSWebpayService?wsdl
   mode: sandbox
   accountid: german-facilitator@arriendas.cl 
   username: german-facilitator_api1.arriendas.cl
   password: 1393252897
   signature: An5ns1Kso7MWUdW4ErQKJJJ4qi4-A-SrinBigkhBBcE9C4ov-x6wgP0q
   status_success: Success
   status_success_warning: SuccessWithWarning
   status_failure: Failure
   status_failure_warning: FailureWithWarning
  prod:
   url: http://201.238.207.131:7003/WSWebpayTransaction/cxf/WSWebpayService?wsdl
   mode: live
   accountid: german@arriendas.cl
   username: german_api1.arriendas.cl
   password: JJKXEZAGQAGZ8N2N
   signature: A5dIkGXX9nIXgGhNqUVPEUBr10xMAMoRvtoTwOtRaSEwrhLLd2Q8s.Xf
   status_success: Success
   status_success_warning: SuccessWithWarning
   status_failure: Failure
   status_failure_warning: FailureWithWarning