# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~
security:  ~

# insert your own filters here
paymentSuccessFilter:
    class: checkPaymentSuccessFilter

completeRegisterFilter:
    class:  checkCompleteRegisterFilter

optionsCarFilter:
    class: checkOptionsCarFilter
    enabled: false

completeRegisterCar:
    class: checkCompleteRegisterCar

notificationFilter:
    class: checkNotificationFilter

cache:     ~
execution: ~
